### ISSUE TITLE
CICD : build and deploy containers.

### ISSUE THREAD

**Issue by PratyushChauhan** [tryvinci/LatentSync#1]
pushing to staging builds and deploys a container on gcp.

**Comment by PratyushChauhan** [comment]
build pipeline created, testing for bugs.

**Comment by PratyushChauhan** [comment]
## Solution : Use Custom Metadata for Container Update
Create a more elegant solution using metadata:
```
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "trigger-container-update"
    args:
      - "compute"
      - "instances"
      - "add-metadata"
      - "vinci-vm"
      - "--zone=asia-southeast1-b"
      - "--metadata=container-image=asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-latentsync/image:latest,update-trigger=$(date +%s)"
```
Then on your VM, set up a systemd service or cron job that watches for metadata changes:
bash
```
# On the VM, create /opt/container-updater.sh
#!/bin/bash
METADATA_URL="http://metadata.google.internal/computeMetadata/v1/instance/attributes"
CURRENT_IMAGE=$(curl -H "Metadata-Flavor: Google" "$METADATA_URL/container-image")
TRIGGER=$(curl -H "Metadata-Flavor: Google" "$METADATA_URL/update-trigger")

# Store last trigger to avoid repeated updates
LAST_TRIGGER_FILE="/tmp/last-update-trigger"
if [ -f "$LAST_TRIGGER_FILE" ]; then
    LAST_TRIGGER=$(cat "$LAST_TRIGGER_FILE")
else
    LAST_TRIGGER=""
fi

if [ "$TRIGGER" != "$LAST_TRIGGER" ]; then
    echo "Updating container to $CURRENT_IMAGE"
    docker pull "$CURRENT_IMAGE"
    docker stop vinci-container || true
    docker rm vinci-container || true
    docker run -d --name vinci-container --gpus all -p 8082:8080 "$CURRENT_IMAGE"
    echo "$TRIGGER" > "$LAST_TRIGGER_FILE"
fi
```

**Comment by PratyushChauhan** [comment]
completed

some changes to the files:

```
#!/bin/bash

# Script to check for container update metadata and pull new images
# Designed to run as a cron job
set -e

# Log file
LOG_FILE="./logs/container-updater.log"
METADATA_FILE="./logs/container-metadata.json"
LAST_UPDATE_FILE="./logs/last_update_trigger"

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a $LOG_FILE
}

# Initialize last update trigger if it doesn't exist
if [ ! -f "$LAST_UPDATE_FILE" ]; then
  echo "0" > $LAST_UPDATE_FILE
  log "Initialized last update trigger file"
fi

# Fetch metadata from instance
curl -s "http://metadata.google.internal/computeMetadata/v1/instance/attributes/" \
  -H "Metadata-Flavor: Google" > $METADATA_FILE

# Extract container image and update trigger
CONTAINER_IMAGE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/attributes/container-image" \
  -H "Metadata-Flavor: Google")

UPDATE_TRIGGER=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/attributes/update-trigger" \
  -H "Metadata-Flavor: Google")

# Get last update trigger value
LAST_UPDATE_TRIGGER=$(cat $LAST_UPDATE_FILE)

log "Current container image: $CONTAINER_IMAGE"
log "Current update trigger: $UPDATE_TRIGGER, Last update trigger: $LAST_UPDATE_TRIGGER"

# Check if update is needed
if [ "$UPDATE_TRIGGER" != "$LAST_UPDATE_TRIGGER" ]; then
  log "Update triggered. Pulling new container image: $CONTAINER_IMAGE"
  
  # Pull the latest container image
  docker pull $CONTAINER_IMAGE
  
  # Update the running container
  
  log "Stopping existing container if running..."
  docker stop vinci-latentsync || true
  docker rm vinci-latentsync || true
  
  log "Starting new container..."
  docker run -d \
    --name vinci-latentsync \
    --restart unless-stopped \
    -p 8082:8080 \
    $CONTAINER_IMAGE
  
  log "Container updated successfully"
  
  # Update the last trigger value
  echo "$UPDATE_TRIGGER" > $LAST_UPDATE_FILE
else
  log "No updates needed."
fi

```
```
  - name: "gcr.io/cloud-builders/gcloud"
    id: "trigger-container-update"
    entrypoint: 'bash'
    args:
      - "-c"
      - "gcloud compute instances add-metadata vinci-vm --zone=asia-southeast1-b --metadata=container-image=asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-latentsync/image:latest,update-trigger=$(date +%s)"
```
